
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cine_recensore
    username: root
    password:  Ferrinico92
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update